import React from 'react'

function allabout() {
  return (
    <div className='terms'>
        <h3>
        This document is an electronic record in terms of Information Technology Act,
         2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. 
         This electronic record is generated by a computer system and does not require any physical or digital signatures.

        document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name [www.flipkart.com][www.flipkart.com] (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”)
        </h3>
    </div>

    
  )
}

export default allabout